-- 코드를 작성해주세요
SELECT
    A.ID,
    CASE
        WHEN (A.RNUM/A.TOTAL) <= 0.25 THEN 'CRITICAL'
        WHEN (A.RNUM/A.TOTAL) <= 0.50 THEN 'HIGH'
        WHEN (A.RNUM/A.TOTAL) <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT
          ID,
          ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RNUM,
          COUNT(*) OVER() AS TOTAL
      FROM ECOLI_DATA) AS A
ORDER BY A.ID ASC