-- 코드를 작성해주세요
#SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
SELECT SUM(C.SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_DEPARTMENT A
    JOIN HR_EMPLOYEES B
    ON A.DEPT_ID = B.DEPT_ID
    JOIN HR_GRADE C
    ON B.EMP_NO = C.EMP_NO
WHERE B.EMP_NO = ( SELECT EMP_NO
                   FROM HR_GRADE
                   GROUP BY EMP_NO
                   ORDER BY AVG(SCORE) DESC
                   LIMIT 1 )
GROUP BY EMP_NO